### ISSUE TITLE
Monitor CronJob Execution Fails due to Unauthorized User Error

### ISSUE THREAD

**Issue by tylerstanczak** [IBM/cp4d-monitors#13]
Environment:
OpenShift: 4.8.24
CP4D: 4.0.6
I followed the guide here: https://ibm.github.io/cp4d-monitors/monitors/cp4d-watsonstudio-job-schedule-info/manual/
I have a feeling there is a step missing on the documentation to get this running. =(

CronJob Logs:
```Starting Cloud Pak for Data Watson Studio Runtime usage monitor....
-------------------------------------------------------------
Executing CP4D Monitor python file: /cp4d-monitoring-scripts/cp4d_watsonstudio_job_schedule_info.py
Traceback (most recent call last):
  File "/usr/lib64/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/user-home/_global_/monitors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/user-home/_global_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cp4d-monitoring-scripts/cp4d_watsonstudio_job_schedule_info.py", line 1, in <module>
    from lib import cp4d_monitor
  File "/cp4d-monitoring-scripts/lib/cp4d_monitor.py", line 102, in <module>
    Path(cache_folder).mkdir( parents=True, exist_ok=True )
  File "/usr/lib64/python3.8/pathlib.py", line 1292, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib64/python3.8/pathlib.py", line 1292, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib64/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/user-home'
-------------------------------------------------------------
Exiting Cloud Pak for Data Watson Studio Runtime usage monitor....```

**Comment by arthurlaimbock** [comment]
Hi Tyler, I will investigate this.

**Comment by arthurlaimbock** [comment]
@tylerstanczak  can you confirm the following patch was performed? 
```
oc patch cronjob -n ${CP4D_PROJECT} ${CP4D_CRONJOB} \
--type=json \
--patch '[{"op": "add","path": "/spec/jobTemplate/spec/template/spec/containers/0/volumeMounts/-","value": {"name": "user-home-mount","mountPath": "/user-home"}}]'
```

you can do `oc edit cronjob <cronjob>` and ensure the volumeMounts is specified.

**Comment by tylerstanczak** [comment]
Thank you @arthurlaimbock that seemed to resolve the above error.
However, a new error now appears:

```
Starting Cloud Pak for Data Watson Studio Runtime usage monitor....
-------------------------------------------------------------
Executing CP4D Monitor python file: /cp4d-monitoring-scripts/cp4d_watsonstudio_job_schedule_info.py
Got error for the command: "/opt/app-root/bin/cpdctl project list --context default --output json"
Please refer to the response for details: FAILED
Error processing the response received, most likely an error response:
{"_statusCode_":401,"exception":"User unauthorized to invoke this endpoint.","message":"Unauthorized"}



Got error to list all projects.
Traceback (most recent call last):
  File "/cp4d-monitoring-scripts/cp4d_watsonstudio_job_schedule_info.py", line 169, in <module>
    main()
  File "/cp4d-monitoring-scripts/cp4d_watsonstudio_job_schedule_info.py", line 31, in main
    projects = cp4d_monitor.get_project_list()
  File "/cp4d-monitoring-scripts/lib/cp4d_monitor.py", line 126, in get_project_list
    if project_data['total_results'] > 0:
TypeError: list indices must be integers or slices, not str
-------------------------------------------------------------
Exiting Cloud Pak for Data Watson Studio Runtime usage monitor....
```

Is this something you've seen before?

**Comment by arthurlaimbock** [comment]
yes, did you update the admin password? If so, please update the admin-user-details secret. Or is the admin user disabled?

**Comment by tylerstanczak** [comment]
It appears that our admin user was disabled. Thanks for the tip Arthur! 😄
